---

- name: Copy kube manifest file for "exporter_hpilo"
  ansible.builtin.copy:
    src: "{{ exporter_hpilo_container_files_path }}/container_{{ exporter_hpilo_container_files_path }}.yml"
    dest: "/etc/containers/systemd/container_{{ exporter_hpilo_container_files_path }}.yml"
    mode: "0644"
    owner: "{{ container_deploy_user | default('root') }}"
    group: "root"

- name: Copy quadlet file for "exporter_hpilo"
  ansible.builtin.copy:
    src: "{{ exporter_hpilo_container_files_path }}/container_{{ exporter_hpilo_container_files_path }}.kube"
    dest: "/etc/containers/systemd/container_{{ exporter_hpilo_container_files_path }}.kube"
    mode: "0644"
    owner: "root"
    group: "root"
  when: container_deploy_user is not defined or container_deploy_user == "root"

## We have no way of detecting when template image is updated/changed, so we always restart the container
- name: Restart and enable systemd container_{{ exporter_hpilo_container_files_path }}.service
  ansible.builtin.systemd:
    name: "container_{{ exporter_hpilo_container_files_path }}.service"
    enabled: yes
    state: restarted
    daemon_reload: yes
  throttle: 1
  when: container_deploy_user is not defined or container_deploy_user == "root"
