# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: web_gapcheck_configmap
# data:
#   GIT_REPOSITORY: "git@github.deutsche-boerse.de:dev/refinst.gapcheck.git"
#   GIT_BRANCH: "master"
#   GIT_USER_NAME: "refinst-automat"
#   GIT_USER_EMAIL: "front-end-services@deutsche-boerse.com"
#   MYSQL_GAPCHECK_MASTER_DB: "mysql1.ref"
#   MYSQL_GAPCHECK_BACKUP_DB: "mysql2.ref"
#   MYSQL_GAPCHECK_1GBIT_DB: "mysql2.ref"
#   MYSQL_GAPCHECK_READONLY_USERNAME: "{{ }}"
#   MYSQL_GAPCHECK_READONLY_PASSWORD: "{{ }}"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: "web_gapcheck_ssh_private_key"
# type: Opaque
# data:
#   id_rsa: "{{ private_key | b64encode }}"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     volume.podman.io/driver: local
#     volume.podman.io/device: plato.ref:/pcap
#     volume.podman.io/type: nfs
#     volume.podman.io/gid: "65534"
#     volume.podman.io/uid: "65534"
#     volume.podman.io/mount-options: async,ro
#   name: pcap_volume
# spec:
#   accessModes:
#   - ReadOnlyMany
# status: {}
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     volume.podman.io/driver: local
#     volume.podman.io/device: troy.ref:/pcap_backup
#     volume.podman.io/type: nfs
#     volume.podman.io/gid: "65534"
#     volume.podman.io/uid: "65534"
#     volume.podman.io/mount-options: async,ro
#   name: pcap_backup_volume
# spec:
#   accessModes:
#   - ReadOnlyMany
# status: {}
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     volume.podman.io/driver: local
#     volume.podman.io/device: troy.ref:/pcap_1Gbit
#     volume.podman.io/type: nfs
#     volume.podman.io/gid: "65534"
#     volume.podman.io/uid: "65534"
#     volume.podman.io/mount-options: async,ro
#   name: pcap_1Gbit_volume
# spec:
#   accessModes:
#   - ReadOnlyMany
# status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
    volume.podman.io/device: /net/plato/pcap
    volume.podman.io/type: none
    volume.podman.io/mount-options: bind
  name: web_gapcheck_pcap_volume
spec:
  accessModes:
  - ReadOnlyMany
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
    volume.podman.io/device: /net/troy/pcap_backup
    volume.podman.io/type: none
    volume.podman.io/mount-options: bind
  name: web_gapcheck_pcap_backup_volume
spec:
  accessModes:
  - ReadOnlyMany
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
    volume.podman.io/device: /net/troy/pcap_1Gbit
    volume.podman.io/type: none
    volume.podman.io/mount-options: bind
  name: web_gapcheck_pcap_1Gbit_volume
spec:
  accessModes:
  - ReadOnlyMany
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: web_gapcheck-pod
spec:
  hostname: web_gapcheck
  volumes:
  - name: web_gapcheck_pcap_volume
    persistentVolumeClaim:
      claimName: web_gapcheck_pcap_volume
      accessModes: ReadOnlyMany
  - name: web_gapcheck_pcap_backup_volume
    persistentVolumeClaim:
      claimName: web_gapcheck_pcap_backup_volume
      accessModes: ReadOnlyMany
  - name: web_gapcheck_pcap_1Gbit_volume
    persistentVolumeClaim:
      claimName: web_gapcheck_pcap_1Gbit_volume
      accessModes: ReadOnlyMany
  - name: web_gapcheck_repository_volume
    emptyDir: {}
  - name: web_gapcheck_ssh_private_key_volume
    secret:
      secretName: web_gapcheck_ssh_private_key
      defaultMode: 0600
  initContainers:
  - name: web_gapcheck_clone_repository
    spec:
      restartPolicy: Never
    image: refinst-docker-dev-local.artifactory.dbgcloud.io/refinst_ubi9_latest:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: web_gapcheck_repository_volume
      mountPath: /repository
    - name: web_gapcheck_ssh_private_key_volume
      mountPath: /root/.ssh/id_rsa
      subPath: id_rsa
    envFrom:
    - secretRef:
        name: web_gapcheck_configmap
    command:
    - 'sh'
    - '-c'
    - >
      ssh-keyscan github.deutsche-boerse.de >> ~/.ssh/known_hosts &&
      git clone --config user.name=$GIT_USER_NAME --config user.email=$GIT_USER_EMAIL --branch $GIT_BRANCH --single-branch $GIT_REPOSITORY /repository
  containers:
  - name: web_gapcheck
    image: refinst-docker-dev-local.artifactory.dbgcloud.io/nginx122_php81:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      hostPort: 8042
    securityContext: {}
    envFrom:
    - secretRef:
        name: web_gapcheck_configmap
    volumeMounts:
    - mountPath: /var/www/html/pcap
      name: web_gapcheck_pcap_volume
      readOnly: true
    - mountPath: /var/www/html/pcap_backup
      name: web_gapcheck_pcap_backup_volume
      readOnly: true
    - mountPath: /var/www/html/pcap_1Gbit
      name: web_gapcheck_pcap_1Gbit_volume
      readOnly: true
    - name: web_gapcheck_repository_volume
      mountPath: /var/www/html
