
---

version: "3.6"

networks:
  docker_bridge:
    name: docker_bridge
    driver: bridge

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400/tcp
    devices:
     - /dev/dri:/dev/dri #Required for plex HW transcoding / QuickSync
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
      - /opt/xmltv_data:/data
    networks:
      - docker_bridge
    restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    ports:
      - 8080:8080
    volumes:
      - ${BASE_PATH}/sabnzbd/config:/config
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
      - /opt/sab_video_downloads:/video_downloads
      - /opt/sab_incomplete_downloads:/incomplete-downloads
      - /opt/sab_radarr_downloads:/radarr_downloads
      - /opt/sab_sonarr_downloads:/sonarr_downloads
      - /opt/sab_misc_downloads:/misc_downloads
    networks:
      - docker_bridge
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${BASE_PATH}/radarr/config:/config
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
      - /opt/sab_radarr_downloads:/radarr_downloads
    ports:
      - 7878:7878
    networks:
      - docker_bridge
    restart: always
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${BASE_PATH}/sonarr/config:/config
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
      - /opt/sab_sonarr_downloads:/sonarr_downloads
    ports:
      - 8989:8989
    networks:
      - docker_bridge
    restart: always

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${BASE_PATH}/tautulli:/config
    ports:
      - 8181:8181
    networks:
      - docker_bridge
    restart: always

  # tdarr: # transcode videos automatically
  #   container_name: tdarr
  #   image: ghcr.io/haveagitgat/tdarr:latest
  #   restart: always
  #   ports:
  #     - 8265:8265 # webUI port
  #     - 8266:8266 # server port
  #   environment:
  #     - TZ=CET
  #     - PUID=1000
  #     - PGID=1000
  #     - UMASK_SET=002
  #     - nodeName=ServerNode
  #     - serverIP=0.0.0.0
  #     - serverPort=8266
  #     - webUIPort=8265
  #     - internalNode=true
  #     - inContainer=true
  #     - ffmpegVersion=6
  #   volumes:
  #     - ${BASE_PATH}/tdarr/server:/app/server
  #     - ${BASE_PATH}/tdarr/configs:/app/configs
  #     - ${BASE_PATH}/tdarr/logs:/app/logs
  #     - ${SHARE}/10tb:/10tb
  #     - ${SHARE}/10tb2:/10tb2
  #     - /transcode_cache:/temp
  #   devices:
  #    - /dev/dri:/dev/dri #Required for HW transcoding / QuickSync
  #   networks:
  #     - docker_bridge

  webgrabplus:
    image: lscr.io/linuxserver/webgrabplus:latest
    container_name: webgrabplus
    hostname: webgrabplus
    mac_address: 02:42:ac:11:ff:ff
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${BASE_PATH}/webgrabplus/config:/config
      - /opt/xmltv_data:/data
    command: /app/update.sh
    networks:
      - docker_bridge

  fileflows:
    image: revenz/fileflows
    container_name: fileflows
    environment:
      - TZ=CET
      - TempPathHost=/opt/containers/fileflows/temp
    volumes:
      # - /run/podman/podman.sock:/var/run/docker.sock:ro
      - /opt/containers/fileflows/data:/app/Data
      - /opt/containers/fileflows/logs:/app/Logs
      - /opt/containers/fileflows/temp:/temp
      - ${SHARE}/10tb:/media
    ports:
      - 19200:5000
    restart: unless-stopped
    devices:
     - /dev/dri:/dev/dri

  #Bazarr - subtitles
  # bazarr:
  #   container_name: bazarr
  #   image: lscr.io/linuxserver/bazarr:latest
  #   restart: always
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=CET
  #   volumes:
  #     - ${BASE_PATH}/bazarr/config:/config
  #     - ${SHARE}/10tb:/10tb
  #     - ${SHARE}/10tb2:/10tb2
  #   ports:
  #     - 6767:6767
  #   networks:
  #     - docker_bridge
