
---
version: "2.1"

services:
  #Plex - media server
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400/tcp
    devices:
     - /dev/dri:/dev/dri #Required for plex HW transcoding / QuickSync
    volumes:
      - ${BASE_PATH}/plex/config:/config
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    ports:
      - 8080:8080
    volumes:
      - ${BASE_PATH}/sabnzbd/config:/config
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
      - /opt/sab_video_downloads:/video_downloads
      - /opt/sab_incomplete_downloads:/incomplete-downloads
      - /opt/sab_radarr_downloads:/radarr_downloads
      - /opt/sab_sonarr_downloads:/sonarr_downloads
      - /opt/sab_misc_downloads:/misc_downloads
    restart: unless-stopped

  #Radarr - movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${BASE_PATH}/radarr/config:/config
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
      - /opt/sab_radarr_downloads:/radarr_downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    
  #Sonarr - tv shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${BASE_PATH}/sonarr/config:/config
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
      - /opt/sab_sonarr_downloads:/sonarr_downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  #Tautulli - plex statistics
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ${BASE_PATH}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  #Tdarr - to transcode videos automatically
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=CET
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=ServerNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
    volumes:
      - ${BASE_PATH}/tdarr/server:/app/server
      - ${BASE_PATH}/tdarr/configs:/app/configs
      - ${BASE_PATH}/tdarr/logs:/app/logs
      - ${SHARE}/10tb:/10tb
      - ${SHARE}/10tb2:/10tb2
      - /transcode_cache:/temp
    devices:
     - /dev/dri:/dev/dri #Required for HW transcoding / QuickSync
      
  #Bazarr - subtitles
  # bazarr:
  #   container_name: bazarr
  #   image: lscr.io/linuxserver/bazarr:latest
  #   restart: unless-stopped
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=CET
  #   volumes:
  #     - ${BASE_PATH}/bazarr/config:/config
  #     - ${SHARE}/10tb:/10tb
  #     - ${SHARE}/10tb2:/10tb2
  #   ports:
  #     - 6767:6767
