---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-vmware-configmap
data:
  VSPHERE_HOST: "refinst-vcenter.ref"
  VSPHERE_IGNORE_SSL: "TRUE"
  VSPHERE_FETCH_ALARMS: "TRUE"
  VSPHERE_COLLECT_RESOURCEPOOLS: "FALSE"
---
apiVersion: v1
kind: Pod
metadata:
  name: exporter_vmware-pod
spec:
  containers:
  - name: exporter_vmware
    image: refinst-docker-dev-local.artifactory.dbgcloud.io/vmware_exporter_latest:latest
    imagePullPolicy: Always
    securityContext: {}
    resources:
      limits:
        memory: "2Gi"
        cpu: "2000m"
    ports:
    - containerPort: 9272
    command: ["/usr/local/bin/vmware_exporter/run"]
    env:
    - name: VSPHERE_USER
      valueFrom:
        secretKeyRef:
          name: vmware_readonly_username
          key: secret
    - name: VSPHERE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: vmware_readonly_password
          key: secret
    - name: VSPHERE_HOST
      valueFrom:
        configMapKeyRef:
          name: exporter-vmware-configmap
          key: VSPHERE_HOST
    - name: VSPHERE_IGNORE_SSL
      valueFrom:
        configMapKeyRef:
          name: exporter-vmware-configmap
          key: VSPHERE_IGNORE_SSL
    - name: VSPHERE_FETCH_ALARMS
      valueFrom:
        configMapKeyRef:
          name: exporter-vmware-configmap
          key: VSPHERE_FETCH_ALARMS
    - name: VSPHERE_COLLECT_RESOURCEPOOLS
      valueFrom:
        configMapKeyRef:
          name: exporter-vmware-configmap
          key: VSPHERE_COLLECT_RESOURCEPOOLS
