# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: web_rds_configmap
# data:
#   GIT_REPOSITORY: "git@github.deutsche-boerse.de:dev/refinst.rds.git"
#   GIT_DESTINATION: "/repository"
#   GIT_BRANCH: "master"
#   GIT_USER_NAME: "refinst-automat"
#   GIT_USER_EMAIL: "front-end-services@deutsche-boerse.com"
#   MYSQL_RDS_DB: "mysql1.ref"
#   MYSQL_RDS_READONLY_USERNAME: "{{ }}"
#   MYSQL_RDS_READONLY_PASSWORD: "{{ }}"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: "web_rds_ssh_private_key"
# type: Opaque
# data:
#   id_rsa: "{{ private_key | b64encode }}"
---
apiVersion: v1
kind: Pod
metadata:
  name: web_rds-pod
spec:
  hostname: web_rds
  volumes:
  - name: web_rds_repository_volume
    emptyDir: {}
  - name: web_rds_ssh_private_key_volume
    secret:
      secretName: web_rds_ssh_private_key
      defaultMode: 0600
  initContainers:
  - name: web_rds_clone_repository
    spec:
      restartPolicy: Never
    image: refinst-docker-dev-local.artifactory.dbgcloud.io/refinst_ubi9_latest:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: web_rds_repository_volume
      mountPath: /repository
    - name: web_rds_ssh_private_key_volume
      mountPath: /root/.ssh/id_rsa
      subPath: id_rsa
    envFrom:
    - secretRef:
        name: web_rds_configmap
    command:
    - 'sh'
    - '-c'
    - >
      ssh-keyscan github.deutsche-boerse.de >> ~/.ssh/known_hosts &&
      git clone --config user.name=$GIT_USER_NAME --config user.email=$GIT_USER_EMAIL --branch $GIT_BRANCH --single-branch $GIT_REPOSITORY /repository
  containers:
  - name: web_rds
    image: refinst-docker-dev-local.artifactory.dbgcloud.io/nginx122_php81:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      hostPort: 8043
    securityContext: {}
    volumeMounts:
    - name: web_rds_repository_volume
      mountPath: /var/www/html
      readOnly: true
    envFrom:
    - secretRef:
        name: web_rds_configmap
