---
apiVersion: v1
kind: ConfigMap
metadata:
  name: refinst-certificates-configmap
data:
  CERTIFICATE_EXPIRY: "30d"
  CERTIFICATE_PATH: "/etc/secrets"
  EXTRA_SAN: "grafana-alloy-cluster.ref"
  PROM_PATH: "/var/log/node_exporter"
  VAULT_ROLENAME: "refinst-ca-role"
---
apiVersion: v1
kind: Pod
metadata:
  name: grafana-alloy-pod
spec:
  hostname: grafana-alloy-{{ inventory_hostname }}
  volumes:
  - name: certificate-volume
    emptyDir: {}
  - name: promfile-volume
    emptyDir: {}
  - name: grafana-alloy-config
    configMap:
      name: grafana-alloy-configmap
    defaultMode: 420
  - name: cisco-snmp-config
    configMap:
      name: cisco-snmp-configmap
    defaultMode: 420
  initContainers:
  - name: refinst_certificate
    image: refinst-docker-dev-local.artifactory.dbgcloud.io/refinst_certificate_latest:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: certificate-volume
      mountPath: /etc/secrets
    - name: promfile-volume
      mountPath: /var/log/node_exporter
    env:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: grafana_alloy_pod_vault_token
          key: secret
    envFrom:
    - configMapRef:
        name: refinst-certificates-configmap
  containers:
  - name: grafana_alloy
    image: refinst-docker-dev-local.artifactory.dbgcloud.io/grafana_alloy_latest:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 12346
      hostPort: 12346
    securityContext: {}
    resources:
      limits:
        memory: "2Gi"
        cpu: "2000m"
    volumeMounts:
    - name: certificate-volume
      mountPath: /etc/secrets
    - name: promfile-volume
      mountPath: /var/log/node_exporter
    - name: grafana-alloy-config
      mountPath: /etc/alloy/config.alloy
      subPath: config.alloy
    - name: cisco-snmp-config
      mountPath: /etc/alloy/cisco_snmp.yml
      subPath: cisco_snmp.yml
    env:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: grafana_alloy_pod_vault_token
          key: secret
    - name: CLUSTER_ADVERTISE_ADDRESS
      value: "{{ init_ifcfg | dict2items | selectattr('key','match', 'ref.*') | map(attribute='value.ipaddr') | first }}:12346"
    args: ["run",
            "--stability.level=experimental",
            "--storage.path=/var/lib/alloy/data",
            "--disable-reporting=true",
            "--server.http.memory-addr=alloy.internal:12347",
            "--server.http.listen-addr=0.0.0.0:12346",
            "--cluster.enabled=true",
            "--cluster.rejoin-interval=60s",
            "--cluster.advertise-address=$(CLUSTER_ADVERTISE_ADDRESS)",
            "--cluster.join-addresses=_grafana_alloy_cluster._tcp.ref",
            "--cluster.enable-tls=true",
            "--cluster.tls-ca-path=/etc/secrets/refinst_ca.crt",
            "--cluster.tls-cert-path=/etc/secrets/refinst_grafana-alloy-{{ inventory_hostname }}.crt",
            "--cluster.tls-key-path=/etc/secrets/refinst_grafana-alloy-{{ inventory_hostname }}.key",
            "--cluster.tls-server-name=grafana-alloy-cluster.ref",
            "/etc/alloy/config.alloy"]
