---

apiVersion: v1
kind: Pod
metadata:
  name: exporter_hpilo-pod
spec:
  containers:
  - name: exporter_hpilo
    image: refinst-docker-dev-local.artifactory.dbgcloud.io/hpilo_exporter_latest:latest
    imagePullPolicy: Always
    securityContext: {}
    ports:
    - containerPort: 9416
    command: ["/usr/local/bin/hpilo-exporter"]
    args: ["--address=0.0.0.0","--port=9416","--endpoint=/metrics"]
